#!/usr/bin/env python3
"""filter-system manage — first-class add / rename / remove / migrate-axis.

Per openspec change formalize-filter-system, Group 5.

Subcommands:
  add-tag <event> <code> <label> [icon] [title]
  add-warning <event> <code> <label> [icon] [class_suffix]
  add-work <event> <code> <label> [icon] [title]
  rename-code <event> <old> <new>
  remove-code <event> <code> [--cleanup]
  migrate-axis <event> --from <axis> --to <axis> <code> [<code> ...]
  migrate-axis <event> --from <axis> --to <axis> --auto-match
      (auto-migrate every <from>-axis code that already exists on <to>)

All commands:
  --dry-run     print plan, no writes
"""

from __future__ import annotations

import argparse
import fcntl
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _filter_lib as fl  # noqa: E402


ALL_AXES = ("cps", "tags", "works", "warnings", "mediums", "areas")


# ---------- read / write helpers ----------

def _read_filters_raw(slug: str) -> tuple[str, dict]:
    """Return (whole_text, parsed_obj). Caller gets the raw text so the
    leading comment block / formatting can be preserved on writeback."""
    path = fl.PROJECT_ROOT / slug / "filters.js"
    text = path.read_text(encoding="utf-8")
    obj = fl._slice_js_object(text, "FILTERS_CONFIG")
    return text, obj


def _write_filters(slug: str, obj: dict) -> None:
    """Serialize `obj` as `window.FILTERS_CONFIG = {...};` and write to
    filters.js, preserving any leading comment block."""
    path = fl.PROJECT_ROOT / slug / "filters.js"
    text = path.read_text(encoding="utf-8")
    m = re.search(r"window\.FILTERS_CONFIG\s*=", text)
    if not m:
        # No preamble — write a default header.
        prefix = (
            "/**\n"
            " * Event-specific filter overrides. Generated by\n"
            " * filter-system manage. Edit via the skill, not by hand.\n"
            " */\n"
        )
    else:
        prefix = text[:m.start()]
    body = json.dumps(obj, ensure_ascii=False, indent=2)
    out = f"{prefix}window.FILTERS_CONFIG = {body};\n"
    with path.open("w", encoding="utf-8") as f:
        fcntl.flock(f.fileno(), fcntl.LOCK_EX)
        try:
            f.write(out)
        finally:
            fcntl.flock(f.fileno(), fcntl.LOCK_UN)


def _rewrite_data_booths(slug: str, mutate_fn) -> int:
    """Read data.js, parse booths, call mutate_fn(b) for each, write back
    with fcntl.flock. mutate_fn should mutate booth in-place. Returns
    number of booths actually changed (mutate_fn signals via the booth
    dict diff)."""
    path = fl.PROJECT_ROOT / slug / "data.js"
    with path.open("r+", encoding="utf-8") as f:
        fcntl.flock(f.fileno(), fcntl.LOCK_EX)
        try:
            raw = f.read()
            m = re.search(r"window\.BOOTHS\s*=\s*(\[)", raw)
            if not m:
                raise ValueError(f"window.BOOTHS not found in {path}")
            arr_start = m.end(1) - 1
            booths = fl._parse_balanced_json_at(raw, arr_start)
            # Find balanced close to know slice end for substitution.
            depth = 0
            arr_end = None
            for i in range(arr_start, len(raw)):
                ch = raw[i]
                if ch == "[":
                    depth += 1
                elif ch == "]":
                    depth -= 1
                    if depth == 0:
                        arr_end = i + 1
                        break
            assert arr_end is not None
            changed = 0
            for b in booths:
                before = json.dumps(b, sort_keys=True)
                mutate_fn(b)
                after = json.dumps(b, sort_keys=True)
                if before != after:
                    changed += 1
            new_arr = json.dumps(booths, ensure_ascii=False, indent=2)
            new_raw = raw[:arr_start] + new_arr + raw[arr_end:]
            f.seek(0)
            f.write(new_raw)
            f.truncate()
            return changed
        finally:
            fcntl.flock(f.fileno(), fcntl.LOCK_UN)


# ---------- code → axis lookup ----------

def _code_axis_map(filters: dict) -> dict[str, str]:
    """Return {code: axis} across all axes of the parsed filters."""
    out: dict[str, str] = {}
    for axis, entries in filters.items():
        for e in entries:
            code = getattr(e, "code", None) if hasattr(e, "code") else e.get("code", "")
            if code:
                out[code] = axis
    return out


# ---------- subcommands ----------

def cmd_add(args, axis: str) -> int:
    """Common add path for tags / warnings / works."""
    filters = fl.load_event_filters(args.event, include_base=True)
    code_axis = _code_axis_map(filters)
    if args.code in code_axis:
        other = code_axis[args.code]
        if other == axis:
            print(f"✗ {args.event}: code '{args.code}' already exists on {axis} axis",
                  file=sys.stderr)
        else:
            print(f"✗ {args.event}: code '{args.code}' already exists on "
                  f"{other} axis — use that axis or rename",
                  file=sys.stderr)
        return 2
    entry = {"code": args.code, "label": args.label}
    if args.icon:
        entry["icon"] = args.icon
    if axis == "warnings" and args.class_suffix:
        entry["class_suffix"] = args.class_suffix
    elif args.title:
        entry["title"] = args.title
    plan = f"add {axis}.{args.code} ({args.label}) to {args.event}"
    if args.dry_run:
        print(f"DRY-RUN: {plan}")
        return 0
    text, obj = _read_filters_raw(args.event)
    obj.setdefault(axis, []).append(entry)
    _write_filters(args.event, obj)
    print(f"✓ {plan}")
    return 0


def cmd_rename_code(args) -> int:
    text, obj = _read_filters_raw(args.event)
    # Where does old live?
    found_axis = None
    for axis in ALL_AXES:
        for e in obj.get(axis, []):
            if e.get("code") == args.old:
                found_axis = axis
                break
        if found_axis:
            break
    if not found_axis:
        print(f"✗ {args.event}: code '{args.old}' not found in filters.js",
              file=sys.stderr)
        return 2

    # Check new doesn't collide
    filters = fl.load_event_filters(args.event, include_base=True)
    code_axis = _code_axis_map(filters)
    if args.new in code_axis:
        print(f"✗ {args.event}: target code '{args.new}' already exists on "
              f"{code_axis[args.new]} axis", file=sys.stderr)
        return 2

    plan = (f"rename {args.event}.{found_axis}.{args.old} → {args.new}; "
            f"rewrite data.js booth refs in same axis")
    if args.dry_run:
        # Count affected booths
        booths = fl.load_event_booths(args.event)
        booth_hits = 0
        for b in booths:
            used = fl.codes_in_booth(b)
            if args.old in used.get(found_axis, []):
                booth_hits += 1
        print(f"DRY-RUN: {plan} ({booth_hits} booth(s) would change)")
        return 0

    # Update filters.js
    for e in obj[found_axis]:
        if e.get("code") == args.old:
            e["code"] = args.new
    _write_filters(args.event, obj)

    # Update data.js
    def mutate(b):
        if found_axis == "cps":
            if isinstance(b.get("cps"), list):
                b["cps"] = [args.new if c == args.old else c for c in b["cps"]]
        elif found_axis == "tags":
            tags = b.get("tags") or {}
            if args.old in tags:
                tags[args.new] = tags.pop(args.old)
        elif found_axis == "warnings":
            warns = b.get("warnings") or []
            new_warns = []
            for w in warns:
                if isinstance(w, str) and w == args.old:
                    new_warns.append(args.new)
                elif isinstance(w, list) and w and w[0] == args.old:
                    new_warns.append([args.new] + w[1:])
                else:
                    new_warns.append(w)
            b["warnings"] = new_warns
    changed = _rewrite_data_booths(args.event, mutate)
    print(f"✓ {plan}; {changed} booth(s) updated")
    return 0


def cmd_remove_code(args) -> int:
    text, obj = _read_filters_raw(args.event)
    found_axis = None
    for axis in ALL_AXES:
        for e in obj.get(axis, []):
            if e.get("code") == args.code:
                found_axis = axis
                break
        if found_axis:
            break
    if not found_axis:
        print(f"✗ {args.event}: code '{args.code}' not in filters.js",
              file=sys.stderr)
        return 2

    booths = fl.load_event_booths(args.event)
    booth_users = []
    for b in booths:
        used = fl.codes_in_booth(b)
        if args.code in used.get(found_axis, []):
            booth_users.append(b["booth_id"])

    if booth_users and not args.cleanup:
        print(f"✗ {args.event}: {len(booth_users)} booth(s) still use "
              f"'{args.code}': {booth_users[:5]}{'...' if len(booth_users) > 5 else ''}",
              file=sys.stderr)
        print(f"  pass --cleanup to strip booth refs too", file=sys.stderr)
        return 2

    plan = f"remove {args.event}.{found_axis}.{args.code}"
    if booth_users:
        plan += f" + strip from {len(booth_users)} booth(s)"
    if args.dry_run:
        print(f"DRY-RUN: {plan}")
        return 0

    obj[found_axis] = [e for e in obj[found_axis] if e.get("code") != args.code]
    _write_filters(args.event, obj)

    if booth_users:
        def mutate(b):
            if found_axis == "cps":
                b["cps"] = [c for c in (b.get("cps") or []) if c != args.code]
            elif found_axis == "tags":
                tags = b.get("tags") or {}
                tags.pop(args.code, None)
            elif found_axis == "warnings":
                warns = b.get("warnings") or []
                b["warnings"] = [
                    w for w in warns
                    if not (
                        (isinstance(w, str) and w == args.code)
                        or (isinstance(w, list) and w and w[0] == args.code)
                    )
                ]
        changed = _rewrite_data_booths(args.event, mutate)
        print(f"✓ {plan} ({changed} booth(s) updated)")
    else:
        print(f"✓ {plan}")
    return 0


def cmd_migrate_axis(args) -> int:
    """Move codes from one axis to another in filters.js + rewrite data."""
    text, obj = _read_filters_raw(args.event)

    # Resolve targets — auto or explicit
    if args.auto_match:
        # Auto: every code currently in <to> axis (per filters merged with
        # base) that ALSO appears as a tag in any booth's `<from>`-axis
        # data goes auto. The deterministic intent: "user already declared
        # this code as a <to>; don't relitigate; migrate booth data".
        merged = fl.load_event_filters(args.event, include_base=True)
        to_codes = {e.code for e in merged.get(args.to, [])}
        booths = fl.load_event_booths(args.event)
        targets = set()
        for b in booths:
            used = fl.codes_in_booth(b)
            for c in used.get(args.from_axis, []):
                if c in to_codes:
                    targets.add(c)
        codes = sorted(targets)
        if not codes:
            print(f"  (auto-match: no codes in booth `{args.from_axis}` "
                  f"data that exist as `{args.to}` filter entries)")
            return 0
    else:
        codes = args.codes

    if not codes:
        print("✗ no codes specified (use --auto-match or list codes positionally)",
              file=sys.stderr)
        return 2

    # Count affected booths
    booths = fl.load_event_booths(args.event)
    code_booth_hits: dict[str, list[str]] = {c: [] for c in codes}
    for b in booths:
        used = fl.codes_in_booth(b)
        for c in codes:
            if c in used.get(args.from_axis, []):
                code_booth_hits[c].append(b["booth_id"])

    plan = (f"migrate axes {args.event}: {args.from_axis} → {args.to} for "
            f"{len(codes)} code(s)")
    if args.dry_run:
        print(f"DRY-RUN: {plan}")
        for c in codes:
            print(f"  {c}: {len(code_booth_hits[c])} booth(s) affected")
        return 0

    # 1. Update filters.js — move any entry whose code matches from
    #    `from_axis` to `to_axis` (creating if absent in `to`)
    code_set = set(codes)
    from_axis_entries = obj.get(args.from_axis, []) or []
    to_axis_entries = obj.get(args.to, []) or []
    moved_entries = []
    kept_from = []
    for e in from_axis_entries:
        if e.get("code") in code_set:
            moved_entries.append(e)
        else:
            kept_from.append(e)
    # Avoid duplicating into `to` if already present
    existing_to_codes = {e.get("code") for e in to_axis_entries}
    for e in moved_entries:
        if e.get("code") not in existing_to_codes:
            to_axis_entries.append(e)
    obj[args.from_axis] = kept_from
    obj[args.to] = to_axis_entries
    _write_filters(args.event, obj)

    # 2. Rewrite data.js booth refs
    def mutate(b):
        # Read from-axis codes off the booth (different shape per axis)
        # then write into to-axis codes.
        from_codes = set()
        if args.from_axis == "tags":
            tags = b.get("tags") or {}
            for c in list(tags.keys()):
                if c in code_set and tags[c]:
                    from_codes.add(c)
                    tags.pop(c, None)
        elif args.from_axis == "cps":
            cps = b.get("cps") or []
            new_cps = []
            for c in cps:
                if c in code_set:
                    from_codes.add(c)
                else:
                    new_cps.append(c)
            b["cps"] = new_cps
        elif args.from_axis == "warnings":
            warns = b.get("warnings") or []
            kept = []
            for w in warns:
                code = w[0] if isinstance(w, list) else w
                if code in code_set:
                    from_codes.add(code)
                else:
                    kept.append(w)
            b["warnings"] = kept
        # write into to-axis
        for c in from_codes:
            if args.to == "tags":
                tags = b.setdefault("tags", {})
                tags[c] = True
            elif args.to == "works":
                works = b.setdefault("works", [])
                if c not in works:
                    works.append(c)
            elif args.to == "cps":
                cps = b.setdefault("cps", [])
                if c not in cps:
                    cps.append(c)
            elif args.to == "warnings":
                warns = b.setdefault("warnings", [])
                if c not in warns:
                    warns.append(c)
    changed = _rewrite_data_booths(args.event, mutate)
    print(f"✓ {plan}; {changed} booth(s) updated")
    return 0


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    for axis, sub_name in [("tags", "add-tag"), ("warnings", "add-warning"),
                            ("works", "add-work")]:
        a = sub.add_parser(sub_name)
        a.add_argument("event")
        a.add_argument("code")
        a.add_argument("label")
        a.add_argument("icon", nargs="?", default="")
        a.add_argument("title", nargs="?", default="")
        a.add_argument("--class-suffix", default="")
        a.add_argument("--dry-run", action="store_true")
        a.set_defaults(handler=lambda args, ax=axis: cmd_add(args, ax))

    r = sub.add_parser("rename-code")
    r.add_argument("event")
    r.add_argument("old")
    r.add_argument("new")
    r.add_argument("--dry-run", action="store_true")
    r.set_defaults(handler=cmd_rename_code)

    rm = sub.add_parser("remove-code")
    rm.add_argument("event")
    rm.add_argument("code")
    rm.add_argument("--cleanup", action="store_true",
                    help="Also strip the code from every booth's data")
    rm.add_argument("--dry-run", action="store_true")
    rm.set_defaults(handler=cmd_remove_code)

    mi = sub.add_parser("migrate-axis")
    mi.add_argument("event")
    mi.add_argument("--from", dest="from_axis", required=True, choices=ALL_AXES)
    mi.add_argument("--to", required=True, choices=ALL_AXES)
    mi.add_argument("--auto-match", action="store_true",
                    help="Move every code in booth `<from>`-axis data that "
                         "already exists as a `<to>`-axis filter entry "
                         "(merged with base)")
    mi.add_argument("--codes", nargs="+", default=[],
                    help="Explicit code(s) to migrate (alternative to --auto-match)")
    mi.add_argument("--dry-run", action="store_true")
    mi.set_defaults(handler=cmd_migrate_axis)

    args = p.parse_args()
    sys.exit(args.handler(args))


if __name__ == "__main__":
    main()
