/* C108 sub-map system — event-specific behaviour (docs/FEATURES.md:
 * "When you need event-specific behaviour beyond DOM presence").
 * Lives entirely here, NOT in shared app.js (which only exposes the
 * generic window.refreshVenueMap() hook).
 *
 * Two controls, rendered into the map section:
 *   1. Sub-map selector — an EXCLUSIVE, higher-level choice of which
 *      建物 (展示棟) floor map to show: 会場全体図 / 南 / 東 / 西. Not a
 *      filter; picking one swaps the displayed map (+ its booth coords).
 *   2. カード連動 toggle — auto | all:
 *        auto = the booth cards + filter counts also scope to the
 *               selected 展示棟 (reusing the existing area filter as the
 *               hidden scoping mechanism — booth.area + filters.js areas).
 *        all  = cards stay all 23; only the map view changes.
 *
 * The map itself shows positions only (space codes); circle names live
 * in the booth cards. Clicking a booth on the map opens its card via the
 * shared overlay.
 *
 * Map data comes from maps.js → window.AREA_MAPS (generated by
 * build_c108_map.py).
 */
(function () {
  var MAPS = window.AREA_MAPS;
  if (!MAPS) return;

  var AREAS = ['minami', 'higashi', 'nishi'];
  var LABELS = { overview: '会場全体図', minami: '南展示棟',
                 higashi: '東展示棟', nishi: '西展示棟' };

  var sel = 'overview';        // active sub-map (exclusive)
  var linkMode = 'auto';       // 'auto' | 'all'
  var current = '__init__';    // last applied map key

  // ---- hidden scoping mechanism: the existing area filter --------------
  function clearAreaFilter() {
    document.querySelectorAll(
      '#filters-area .filter-btn.active[data-filter^="area:"]'
    ).forEach(function (b) { b.click(); });
  }
  function setAreaFilter(area) {
    var want = 'area:' + area;
    document.querySelectorAll('#filters-area .filter-btn[data-filter^="area:"]')
      .forEach(function (b) {
        var on = b.classList.contains('active');
        var isWant = b.getAttribute('data-filter') === want;
        if (isWant && !on) b.click();
        else if (!isWant && on) b.click();
      });
  }
  function applyScope() {
    if (linkMode === 'auto' && sel !== 'overview') setAreaFilter(sel);
    else clearAreaFilter();
  }

  // ---- map swap --------------------------------------------------------
  function swapMap() {
    var key = MAPS[sel] ? sel : 'default';
    if (sel === 'overview') key = 'default';
    if (key === current) { renderRegions(sel === 'overview'); return; }
    current = key;
    var conf = MAPS[key] || MAPS.default || {};
    var img = document.getElementById('venue-map');
    if (img && conf.image) {
      var prev = new URL(img.src, location.href);
      var next = new URL(conf.image, location.href);
      if (!next.search && prev.search) next.search = prev.search;
      img.src = next.pathname + next.search;
    }
    window.BOOTH_COORDS = conf.coords || {};
    if (typeof window.refreshVenueMap === 'function') window.refreshVenueMap();
    renderRegions(sel === 'overview');
  }

  function selectSubmap(id) {
    sel = id;
    Array.prototype.forEach.call(
      document.querySelectorAll('.submap-tab'),
      function (b) { b.classList.toggle('active', b.dataset.sub === id); });
    swapMap();
    applyScope();
    try { localStorage.setItem('c108-submap', id); } catch (e) {}
  }

  function setLinkMode(m) {
    linkMode = m;
    Array.prototype.forEach.call(
      document.querySelectorAll('.submap-link-btn'),
      function (b) { b.classList.toggle('active', b.dataset.mode === m); });
    applyScope();
    try { localStorage.setItem('c108-linkmode', m); } catch (e) {}
  }

  // ---- overview clickable building regions → select that sub-map -------
  function renderRegions(show) {
    var svg = document.getElementById('venue-map-overlay');
    if (!svg) return;
    var old = svg.querySelector('g.area-targets');
    if (old) old.remove();
    var regions = (MAPS.default && MAPS.default.regions) || null;
    if (!show || !regions) return;
    var ns = 'http://www.w3.org/2000/svg';
    var g = document.createElementNS(ns, 'g');
    g.setAttribute('class', 'area-targets');
    Object.keys(regions).forEach(function (area) {
      var r = regions[area];
      var rect = document.createElementNS(ns, 'rect');
      rect.setAttribute('x', r.x); rect.setAttribute('y', r.y);
      rect.setAttribute('width', r.w); rect.setAttribute('height', r.h);
      rect.setAttribute('class', 'area-target');
      rect.setAttribute('data-area', area);
      g.appendChild(rect);
    });
    svg.insertBefore(g, svg.firstChild);
  }
  document.addEventListener('click', function (e) {
    var tgt = e.target.closest && e.target.closest('rect.area-target');
    if (!tgt) return;
    e.stopPropagation();
    selectSubmap(tgt.getAttribute('data-area'));
  });

  // ---- build the controls UI ------------------------------------------
  function buildControls(titleEl) {
    var wrap = document.createElement('div');
    wrap.className = 'submap-controls';

    var tabs = document.createElement('div');
    tabs.className = 'submap-tabs';
    tabs.setAttribute('role', 'tablist');
    ['overview'].concat(AREAS).forEach(function (id) {
      var b = document.createElement('button');
      b.type = 'button';
      b.className = 'submap-tab';
      b.dataset.sub = id;
      b.setAttribute('role', 'tab');
      b.textContent = LABELS[id];
      b.addEventListener('click', function () { selectSubmap(id); });
      tabs.appendChild(b);
    });

    var link = document.createElement('div');
    link.className = 'submap-link';
    var lab = document.createElement('span');
    lab.className = 'submap-link-label';
    lab.textContent = 'カード連動';
    link.appendChild(lab);
    [['auto', '連動'], ['all', '全件']].forEach(function (pair) {
      var b = document.createElement('button');
      b.type = 'button';
      b.className = 'submap-link-btn';
      b.dataset.mode = pair[0];
      b.textContent = pair[1];
      b.title = pair[0] === 'auto'
        ? '選んだ展示棟にカード一覧も連動'
        : 'カードは全件のまま、マップだけ切替';
      b.addEventListener('click', function () { setLinkMode(pair[0]); });
      link.appendChild(b);
    });

    wrap.appendChild(tabs);
    wrap.appendChild(link);
    titleEl.insertAdjacentElement('afterend', wrap);
  }

  // ---- boot ------------------------------------------------------------
  function ready() {
    return typeof window.refreshVenueMap === 'function' &&
      document.getElementById('map-section-title') &&
      document.querySelector('#filters-area .filter-btn[data-filter^="area:"]');
  }
  function boot(tries) {
    if (!ready()) {
      if (tries > 60) return;
      setTimeout(function () { boot(tries + 1); }, 100);
      return;
    }
    // The area filter is the hidden scoping mechanism — its row is not a
    // user-facing control here (the sub-map selector replaces it).
    var arearow = document.getElementById('filters-area');
    if (arearow) arearow.style.display = 'none';

    buildControls(document.getElementById('map-section-title'));

    var savedSub = 'overview', savedMode = 'auto';
    try {
      var s = localStorage.getItem('c108-submap');
      if (s && (s === 'overview' || AREAS.indexOf(s) >= 0)) savedSub = s;
      var m = localStorage.getItem('c108-linkmode');
      if (m === 'auto' || m === 'all') savedMode = m;
    } catch (e) {}
    setLinkMode(savedMode);   // sets buttons (no scope yet — sel=overview)
    selectSubmap(savedSub);   // swaps map + applies scope
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', function () { boot(0); });
  } else {
    boot(0);
  }
})();
