/* C108 per-area map — event-specific behaviour (see docs/FEATURES.md:
 * "When you need event-specific behaviour beyond DOM presence").
 *
 * Comiket spans several buildings, so one map image can't show it all.
 * This script swaps the displayed venue map + its booth coords to match
 * the active 展示棟 *area filter* (the standard filters-area row), reusing
 * the shared map/overlay/click system unchanged. The only shared-app.js
 * touchpoint is window.refreshVenueMap() (re-draws the click overlay
 * after we swap coords).
 *
 * Map data (per-area image + booth coords + overview building regions)
 * comes from maps.js → window.AREA_MAPS, generated by build_c108_map.py.
 *
 * Behaviour:
 *   - exactly one 展示棟 area filter active → show that building's floor
 *     map (booths clickable via the normal overlay)
 *   - none / multiple active → show the 会場全体図 overview, whose
 *     building boxes are clickable shortcuts that toggle the area filter
 * Card scoping + map highlight come for free from the existing area
 * filter — this script only changes which map image/coords are shown.
 */
(function () {
  var MAPS = window.AREA_MAPS;
  if (!MAPS) return;

  function activeArea() {
    var btns = document.querySelectorAll(
      '#filters-area .filter-btn.active[data-filter^="area:"]');
    if (btns.length !== 1) return null;
    return btns[0].getAttribute('data-filter').slice(5); // after "area:"
  }

  var current = '__init__';
  function syncMap() {
    var area = activeArea();
    var key = (area && MAPS[area]) ? area : 'default';
    if (key === current) return;
    current = key;
    var conf = MAPS[key] || MAPS.default || {};
    var img = document.getElementById('venue-map');
    if (img && conf.image) {
      var prev = new URL(img.src, location.href);
      var next = new URL(conf.image, location.href);
      if (!next.search && prev.search) next.search = prev.search;
      img.src = next.pathname + next.search;
    }
    window.BOOTH_COORDS = conf.coords || {};
    if (typeof window.refreshVenueMap === 'function') window.refreshVenueMap();
    renderRegions(key === 'default');
  }

  // Overview: draw clickable building regions over the building boxes.
  function renderRegions(show) {
    var svg = document.getElementById('venue-map-overlay');
    if (!svg) return;
    var old = svg.querySelector('g.area-targets');
    if (old) old.remove();
    var regions = (MAPS.default && MAPS.default.regions) || null;
    if (!show || !regions) return;
    var ns = 'http://www.w3.org/2000/svg';
    var g = document.createElementNS(ns, 'g');
    g.setAttribute('class', 'area-targets');
    Object.keys(regions).forEach(function (area) {
      var r = regions[area];
      var rect = document.createElementNS(ns, 'rect');
      rect.setAttribute('x', r.x); rect.setAttribute('y', r.y);
      rect.setAttribute('width', r.w); rect.setAttribute('height', r.h);
      rect.setAttribute('class', 'area-target');
      rect.setAttribute('data-area', area);
      g.appendChild(rect);
    });
    svg.insertBefore(g, svg.firstChild);
  }

  // Region click → toggle the matching area filter button (which scopes
  // cards + map via the existing filter pipeline; syncMap then swaps img).
  document.addEventListener('click', function (e) {
    var tgt = e.target.closest && e.target.closest('rect.area-target');
    if (!tgt) return;
    e.stopPropagation();
    var area = tgt.getAttribute('data-area');
    var btn = document.querySelector(
      '#filters-area .filter-btn[data-filter="area:' + area + '"]');
    if (btn) btn.click();
  });

  // React to any area-filter button change (app.js updates .active first).
  document.addEventListener('click', function (e) {
    if (e.target.closest && e.target.closest('#filters-area .filter-btn')) {
      setTimeout(syncMap, 0);
    }
  });

  // This script is loaded BEFORE app.js (coords convention), so wait until
  // app.js has initialised: window.refreshVenueMap exists and the area
  // filter buttons have been painted.
  function ready() {
    return typeof window.refreshVenueMap === 'function' &&
      document.querySelector('#filters-area .filter-btn[data-filter^="area:"]');
  }
  function boot(tries) {
    if (ready()) { syncMap(); return; }
    if (tries > 60) return;            // ~6s ceiling, then give up quietly
    setTimeout(function () { boot(tries + 1); }, 100);
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', function () { boot(0); });
  } else {
    boot(0);
  }
})();
