#!/usr/bin/env python3
"""Generate profile-patterns.js from the skill's _PROFILE_PATTERN_SOURCES.

Single source of truth: the skill's gateway patterns are reused on the
frontend for chip-label extraction. Run after changing the patterns in
~/.claude/skills/author-name-resolver/scripts/resolver.py — the JS file
should always match the Python source.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path.home() / '.claude/skills/author-name-resolver/scripts'))
from resolver import _PROFILE_PATTERN_SOURCES

# Convert Python (?P<handle>...) to JS named group (same syntax in modern JS:
# (?<handle>...). The only difference is the P prefix.
entries = []
for plat, py_regex, fmt in _PROFILE_PATTERN_SOURCES:
    js_regex = py_regex.replace('(?P<handle>', '(?<handle>')
    entries.append({'platform': plat, 'regex': js_regex, 'fmt': fmt})

out_path = Path(__file__).parent.parent.parent / 'profile-patterns.js'
js = ('/* AUTO-GENERATED by scripts/gen_profile_patterns_js.py — DO NOT EDIT.\n'
      ' * Single source of truth: skill author-name-resolver _PROFILE_PATTERN_SOURCES.\n'
      ' * Used by app.js + circles/circles.js extractHandleFromUrl().\n'
      ' */\n'
      'window.PROFILE_PATTERNS = ' + json.dumps(entries, ensure_ascii=False, indent=2) + ';\n')
out_path.write_text(js, encoding='utf-8')
print(f'wrote {out_path} ({len(entries)} patterns)')
