window.BOOTHS = [
  {
    "booth_id": "ヤオ01.02",
    "circle_name": "ふわふわパレット",
    "author": "HIRO",
    "x_handle": "fluffy_palette",
    "x_url": "https://x.com/fluffy_palette",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ03",
    "circle_name": "ほっぺ食堂",
    "author": "みちよんぽちゃん",
    "x_handle": "anmitiyon",
    "x_url": "https://x.com/anmitiyon",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ04",
    "circle_name": "めきめき亭",
    "author": "めきめき",
    "x_handle": "mekimekix",
    "x_url": "https://x.com/mekimekix",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ05",
    "circle_name": "あま小屋",
    "author": "あまみつき",
    "x_handle": "amtkmituki",
    "x_url": "https://x.com/amtkmituki",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ06",
    "circle_name": "えんどろ〜る",
    "author": "しょうぽん",
    "x_handle": "shopon1201",
    "x_url": "https://x.com/shopon1201",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ07",
    "circle_name": "巣穴",
    "author": "たぬき",
    "x_handle": "kitanaitanuki",
    "x_url": "https://x.com/kitanaitanuki",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ08",
    "circle_name": "モチ屋",
    "author": "ホシモチ",
    "x_handle": "omochidry",
    "x_url": "https://x.com/omochidry",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ09",
    "circle_name": "さくら研究室",
    "author": "桜真咲",
    "x_handle": "masaki_sakura",
    "x_url": "https://x.com/masaki_sakura",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ10",
    "circle_name": "うじゃと屋",
    "author": "うじゃじゃじゃ",
    "x_handle": "ujat_47",
    "x_url": "https://x.com/ujat_47",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ11",
    "circle_name": "カフェイン中毒",
    "author": "俺俺俺俺",
    "x_handle": "Huskychuk",
    "x_url": "https://x.com/Huskychuk",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ12",
    "circle_name": "東ガル会",
    "author": "快楽園梅香",
    "x_handle": "SENBAKO1",
    "x_url": "https://x.com/SENBAKO1",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ13",
    "circle_name": "GUNP",
    "author": "GUNP",
    "x_handle": "gunp_m",
    "x_url": "https://x.com/gunp_m",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ14",
    "circle_name": "百合喫茶店",
    "author": "ビー",
    "x_handle": "yurikissaten",
    "x_url": "https://x.com/yurikissaten",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ15",
    "circle_name": "なむあーる",
    "author": "ちゃなつ!",
    "x_handle": "nanashiwan",
    "x_url": "https://x.com/nanashiwan",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ16",
    "circle_name": "製麺所",
    "author": "めん",
    "x_handle": "A_n_Tu_len",
    "x_url": "https://x.com/A_n_Tu_len",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ17.18",
    "circle_name": "umaura.",
    "author": "るべ",
    "x_handle": "umaauraa5",
    "x_url": "https://x.com/umaauraa5",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ19",
    "circle_name": "しろつめ亭",
    "author": "えいじゅん",
    "x_handle": "EijuneSound",
    "x_url": "https://x.com/EijuneSound",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ20",
    "circle_name": "EXTRA SYSTEM.",
    "author": "YUTO HIGUCHI",
    "x_handle": "YUTO_HIGUCHI_",
    "x_url": "https://x.com/YUTO_HIGUCHI_",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ21",
    "circle_name": "star Kzer",
    "author": "霧崎",
    "x_handle": "star_Kzer",
    "x_url": "https://x.com/star_Kzer",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ22",
    "circle_name": "〜狂堂〜",
    "author": "シミヤ",
    "x_handle": "YukkuriShimiya",
    "x_url": "https://x.com/YukkuriShimiya",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ23",
    "circle_name": "玄米炭酸水",
    "author": "そばがき、巽ぺーた",
    "x_handle": "zuzuzu_222",
    "x_url": "https://x.com/zuzuzu_222",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ24",
    "circle_name": "カゲノテラス",
    "author": "マミハ",
    "x_handle": "",
    "x_url": "",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ25",
    "circle_name": "北のそい屋",
    "author": "そやす",
    "x_handle": "soyas_",
    "x_url": "https://x.com/soyas_",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ26",
    "circle_name": "はっぱどおり",
    "author": "ahonok",
    "x_handle": "",
    "x_url": "",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ27",
    "circle_name": "SPECIAL ONE",
    "author": "えいゆう",
    "x_handle": "Eiyuuu7777",
    "x_url": "https://x.com/Eiyuuu7777",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ28",
    "circle_name": "雛菊書房",
    "author": "小鳥遊 昴",
    "x_handle": "HinagikuBooks",
    "x_url": "https://x.com/HinagikuBooks",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ29",
    "circle_name": "ホワイトフォンダンショコラ",
    "author": "ポポロン",
    "x_handle": "meiliismywife",
    "x_url": "https://x.com/meiliismywife",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ30",
    "circle_name": "沈黙の放課後",
    "author": "つきせ",
    "x_handle": "tukise_after",
    "x_url": "https://x.com/tukise_after",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ31",
    "circle_name": "ネコキャット団",
    "author": "団長",
    "x_handle": "d_tk2",
    "x_url": "https://x.com/d_tk2",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ32",
    "circle_name": "熱帯夜",
    "author": "Atu",
    "x_handle": "Atu_110_011",
    "x_url": "https://x.com/Atu_110_011",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ33",
    "circle_name": "ピアノロック組",
    "author": "ピアノロック・ヤクザ、たっくん",
    "x_handle": "pianorock_y",
    "x_url": "https://x.com/pianorock_y",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ34",
    "circle_name": "papercraft工房おりがみ",
    "author": "イチ",
    "x_handle": "papercraorigami",
    "x_url": "https://x.com/papercraorigami",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ35",
    "circle_name": "ソーイング電柱",
    "author": "おかくま",
    "x_handle": "oka_3d_01",
    "x_url": "https://x.com/oka_3d_01",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  },
  {
    "booth_id": "ヤオ36",
    "circle_name": "にゃんるい会",
    "author": "ステルスにゃんこ、幸春るいか",
    "x_handle": "nyanruikai",
    "x_url": "https://x.com/nyanruikai",
    "body": "",
    "cps": [],
    "tags": {},
    "min_price": null,
    "cover_urls": []
  }
];
